// Code generated by otelwrap; DO NOT EDIT.
// github.com/QuangTung97/otelwrap

package otel

import (
	"context"
	"github.com/ekowdd89/go-kit/internals/db/sqlc"
	"github.com/ekowdd89/go-kit/internals/db/todo"
	"go.opentelemetry.io/otel/codes"
	"go.opentelemetry.io/otel/trace"
)

// TodoContractWrapper wraps OpenTelemetry's span
type TodoContractWrapper struct {
	todo.TodoContract
	tracer trace.Tracer
	prefix string
}

// NewTodoContractWrapper creates a wrapper
func NewTodoContractWrapper(wrapped todo.TodoContract, tracer trace.Tracer, prefix string) *TodoContractWrapper {
	return &TodoContractWrapper{
		TodoContract: wrapped,
		tracer:       tracer,
		prefix:       prefix,
	}
}

// GetByID ...
func (w *TodoContractWrapper) GetByID(ctx context.Context, id int64) (a sqlc.Todo, err error) {
	ctx, span := w.tracer.Start(ctx, w.prefix+"GetByID")
	defer span.End()

	a, err = w.TodoContract.GetByID(ctx, id)
	if err != nil {
		span.RecordError(err)
		span.SetStatus(codes.Error, err.Error())
	}
	return a, err
}

// GetAll ...
func (w *TodoContractWrapper) GetAll(ctx context.Context) (a []sqlc.Todo, err error) {
	ctx, span := w.tracer.Start(ctx, w.prefix+"GetAll")
	defer span.End()

	a, err = w.TodoContract.GetAll(ctx)
	if err != nil {
		span.RecordError(err)
		span.SetStatus(codes.Error, err.Error())
	}
	return a, err
}

// Create ...
func (w *TodoContractWrapper) Create(ctx context.Context, a sqlc.CreateTodoParams) (a1 sqlc.Todo, err error) {
	ctx, span := w.tracer.Start(ctx, w.prefix+"Create")
	defer span.End()

	a1, err = w.TodoContract.Create(ctx, a)
	if err != nil {
		span.RecordError(err)
		span.SetStatus(codes.Error, err.Error())
	}
	return a1, err
}

// Update ...
func (w *TodoContractWrapper) Update(ctx context.Context, a sqlc.UpdateTodoParams) (a1 sqlc.Todo, err error) {
	ctx, span := w.tracer.Start(ctx, w.prefix+"Update")
	defer span.End()

	a1, err = w.TodoContract.Update(ctx, a)
	if err != nil {
		span.RecordError(err)
		span.SetStatus(codes.Error, err.Error())
	}
	return a1, err
}

// Delete ...
func (w *TodoContractWrapper) Delete(ctx context.Context, id int64) (a sqlc.Todo, err error) {
	ctx, span := w.tracer.Start(ctx, w.prefix+"Delete")
	defer span.End()

	a, err = w.TodoContract.Delete(ctx, id)
	if err != nil {
		span.RecordError(err)
		span.SetStatus(codes.Error, err.Error())
	}
	return a, err
}
