# https://taskfile.dev

version: '3'


tasks:
  otelwrapper:
    cmds:
      - go install github.com/QuangTung97/otelwrap@latest && go generate ./... ## install go install github.com/QuangTung97/otelwrap@latest terlebih dahulu
    silent: true
  sqlc:
    cmds:
      - sqlc generate --file ./internals/db/sqlc.yaml
    silent: true
  down:
    cmds:
      - docker compose down --volumes
    silent: true
  up:
    cmds:
      - go mod tidy && docker compose up --build -d
    silent: true
