// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"database/sql"
)

type Author struct {
	ID   int32
	Name sql.NullString
}

type Todo struct {
	ID        int32
	Title     sql.NullString
	Completed sql.NullBool
}
